### ISSUE TITLE
Extraction tests (for complexity of algorithms)

### ISSUE THREAD

**Issue by lasydler** [monadius/coq_codewars#2] opened 2020-02-02 01:07 UTC
Hello,

This is a feature request to add commands inside the plugin (or elsewhere in the tool?) which could compile and execute extracted code. The idea is to use that to test the complexity of algorithms given by users.

I don't know how code is executed inside this plugin but what would be enough for my usage is to redirect the Coq output to some files, then add some text, and compile/execute this file.
```
coqc mytest.v > extracted_code.ml &&
echo "let () = my_function(my_input)" >> extracted_code.ml &&
ocamlc -I zarith extracted_code.ml -o extracted_code.exe &&
./extracted_code.exe > /dev/null
```

Note that a command for compiling extracted code directly inside Coq already exists: `Extraction TestCompile`. I don't know if this can be useful ?

This is, of course, a very low priority problem.

**Comment by monadius** [comment] 2020-02-02 01:31
I am going to work on this feature when I have time. My idea is to implement one new command: `CWCompileAndRun` which takes a list of OCaml files to compile, additional compilation options, and a string which defines the driver code (main function and all tests). Here is an example:

```coq
CWCompileAndRun "extracted_code.ml" Options "-I zarith" Driver "
let () = extracted_function(100)
".
```

I am not sure how to report test results back to Codewars. One option is to print test results directly in the driver code with appropriate Codewars tags. Another option is to capture output inside the plugin command.

**Comment by lasydler** [comment] 2020-02-02 16:53
In my example, we don't need to actually look at the result given by OCaml, we just need to know that it does not timeout. So, this could be a first step.

Also, the "script" I put is a sketch: it may be more difficult to include the options when compiling OCaml than just putting `-I zarith`.

And perhaps the ideal would be:
```
CWExtractCompileAndRun my_ident Options "-I zarith" Driver "
let () = extracted_function(100)
".
```

**Comment by monadius** [comment] 2020-02-07 06:21
I implemented a new command `CWCompileAndRun`.

@kazk When you have time, please test this new command. It should be enough to run `make` for rebuilding the plugin and then to run `make` inside [`cw_example_extraction`](https://github.com/Codewars/coq_codewars/tree/master/cw_example_extraction). This example contains one successful test and one failing test.

**Comment by kazk** [comment] 2020-02-08 03:52
@monadius I had to change `-O3` to `-ccopt -O3` (got unknown option).
```

<IT::>Successful Extraction Test

Running: ocamlopt -ccopt -O3 factorial.mli factorial.ml driver.ml
<PASSED::>OK

Running: ./a.out
<PASSED::>OK


<COMPLETEDIN::>81.46


<IT::>Extraction Test With Errors

Running: ocamlopt -ccopt -O2 factorial.mli factorial.ml driver.ml
<FAILED::>Compilation failed

File "factorial.ml", line 4, characters 14-15:
Error: Syntax error
File "./SolutionTest.v", line 30, characters 0-189:
Error: Compilation failed

```

![image](https://user-images.githubusercontent.com/639336/74078653-e6fc8700-49e1-11ea-9b54-25eb911c43eb.png)

![image](https://user-images.githubusercontent.com/639336/74078647-d8ae6b00-49e1-11ea-93a1-f5e03cd49a39.png)

`<COMPLETEDIN::>` is missing on failure.

---

I might need to change how the container image is built if we need to allow compiling arbitrary OCaml code. I currently have the image optimized for the size and it contains just enough to be used for our purpose. For now, I added `gcc` and some other system libraries to make this example compile.

**Comment by monadius** [comment] 2020-02-08 04:39
@kazk Thank you for testing! Right now `<COMPLETEDIN::>` is not printed on any failure. I will add it.

**Comment by monadius** [comment] 2020-02-08 05:00
I committed new changes. Now `<COMPLETEDIN::>` is printed on failures. I also decided to use `ocamlc` (OCaml bytecode compiler). I think `ocamlc` requires less dependencies than `ocamlopt` and it will be easier to set up a correct container image.

**Comment by kazk** [comment] 2020-02-08 21:23
> I committed new changes. Now `<COMPLETEDIN::>` is printed on failures. 

The output of the test with both failure and success is messed up now.
```coq
(* Preloaded.v *)
Axiom test_axiom : False.
```
```coq
(* Solution.v *)
Require Import Preloaded.
Lemma solution : 1 + 1 = 3.
Proof. firstorder using test_axiom. Qed.
```
```coq
(* SolutionTest.v *)
Require Solution.
Require Import Preloaded.
From CW Require Import Loader.

CWGroup "Tests for Solution.solution".
  CWTest "Type test".
    Fail CWAssert "Should fail" Solution.solution : (1 + 1 = 2).
    CWAssert Solution.solution : (1 + 1 = 3).
  CWEndTest.
  CWTest "Assumptions test".
    CWAssert "Testing solution" Solution.solution Assumes test_axiom.
CWEndGroup.
```
used to output the structure (indented to show the nesting)
```
<DESCRIBE::>
  <IT::>
    <FAILED::>
    <PASSED::>
  <COMPLETEDIN::>
  <IT::>
    <PASSED::>
  <COMPLETEDIN::>
<COMPLETEDIN::>
```
but now it's
```
<DESCRIBE::>
  <IT::>
    <FAILED::>
  <COMPLETEDIN::>
<COMPLETEDIN::>
<PASSED::>
<COMPLETEDIN::>
<IT::>
  <PASSED::>
<COMPLETEDIN::>
<COMPLETEDIN::>
```

You can revert it if this is difficult. It should be displayed decently for most cases. I'm just concerned that if there's another unrelated failing test after it, it'll be confusing.
![image](https://user-images.githubusercontent.com/639336/74092120-c7626e80-4a74-11ea-9fdd-20be030b212e.png)
Note that the error is associated with unrelated test.
![image](https://user-images.githubusercontent.com/639336/74092188-8454cb00-4a75-11ea-9bf8-14c8fdbc6395.png)

This happens because those errors are from `stderr` and it's appended to `stdout` after some processing.

If `<COMPLETEDIN::>` is present, the error will be at top level.
![image](https://user-images.githubusercontent.com/639336/74092229-df86bd80-4a75-11ea-8691-0a91b7b8aadb.png)

![image](https://user-images.githubusercontent.com/639336/74092212-b7975a00-4a75-11ea-9dc3-b1e427c0c38e.png)

**Comment by monadius** [comment] 2020-02-09 01:49
I made the following changes:
1) Added a new command `CWStopOnFailure` which controls whether Coq should be stopped after a failed test or not.
2) Edited `cw_example`: added `CWStopOnFailure 0` and removed `Fail CWAssert`. Now everything should be displayed properly.
3) Added `2>&1` to commands executed by `CWCompileAndRun`. It is not an ideal solution because error messages may be displayed before `Running: ...`. But I think it is not a big issue.

All open groups are still closed with `<COMPLETEDIN::>` on failures (unless `CWStopOnFailure 0` is executed first). Because of this, the final Coq error message will be displayed at top level. But I don't think it will be confusing because no tests can be executed after the first failed test (unless someone writes `Fail ...` which should not be used with the plugin commands).

**Comment by kazk** [comment] 2020-02-12 21:10
`cw_example` is producing different output now.

Original
![image](https://user-images.githubusercontent.com/639336/74376636-5afaae80-4d97-11ea-8474-83c347ff43ae.png)

Now `Assumptions test` have failed and passed.
![image](https://user-images.githubusercontent.com/639336/74376907-cfcde880-4d97-11ea-8f0f-8e2142674ca0.png)

`cw_example_extraction` looks fine now.
![image](https://user-images.githubusercontent.com/639336/74377357-9a75ca80-4d98-11ea-8713-55bbd063878d.png)

**Comment by monadius** [comment] 2020-02-12 21:15
Everything looks good now. I changed `cw_example`: it has 2 failed tests now (one Type Test and one Assumptions Test).

**Comment by kazk** [comment] 2020-02-12 22:00
So having both `failed` and `passed` under `Assumptions test` is expected?
![image](https://user-images.githubusercontent.com/639336/74380876-41f5fb80-4d9f-11ea-8505-2ee786e4e19e.png)

I thought it was some kind of regression because `Assumptions test` only has one `CWAssert` but two results are outputted.
https://github.com/Codewars/coq_codewars/blob/c08b0d9f8d81bd82b3fbf2bb39a2c08668e9ceee/cw_example/SolutionTest.v#L7-L16

**Comment by monadius** [comment] 2020-02-12 22:37
You are right: this behavior is not expected. I committed changes which should fix this bug (which only appeared when the new command `CWStopOnFailure 0` was used). I added new tests to `cw_example`: it has 5 Assumptions tests now (2 should pass and 3 should fail).

**Comment by kazk** [comment] 2020-02-12 22:56
OK, I think it looks good now.
![image](https://user-images.githubusercontent.com/639336/74384761-dfa0f900-4da6-11ea-8483-148477557d1d.png)

**Comment by monadius** [comment] 2020-02-12 23:04
The test output looks good.

**Comment by kazk** [comment] 2020-02-13 20:51
@monadius Do you know why https://www.codewars.com/kata/5e193501bbc85d002c6a6d52 is failing (not outputting `<PASSED::>`)? I'm not sure if it was working with previous version of this plugin. I tested the update against all published Coq kata and this failed.
It's deployed to preview if you want to try. https://preview.codewars.com/kata/5e193501bbc85d002c6a6d52

**Comment by kazk** [comment] 2020-02-13 21:07
> I'm not sure if it was working with previous version of this plugin

It doesn't seem to be related to this update. It was already broken because it doesn't work on the production that uses the previous version.

**Comment by monadius** [comment] 2020-02-13 21:08
It is the only Coq kata which I have not completed yet. But it does not use the plugin.

**Comment by kazk** [comment] 2020-02-13 22:55
Deployed

**Closed as completed by kazk** 2020-02-13 22:55 UTC
Labels: enhancement

**Comment by monadius** [comment] 2020-02-14 00:06
Thank you @kazk! I created a [kumite](https://www.codewars.com/kumite/5e45dcf481a5bd001bf7bffa?sel=5e45dcf481a5bd001bf7bffa) to test new commands. Everything works very well.
